INSERT INTO recipe_label VALUES
('Spinach and Feta Quiche','1'),
('Spinach and Feta Quiche','2'),
('Beef Wellington','3'),
('Chocolate Chip Cookies','4'),
('Chicken Pad Thai','3'),
('Chicken Pad Thai','5'),
('Croissant','6'),
('Croissant','5'),
('Tiramisu','4'),
('Sushi Rolls','2'),
('Sushi Rolls','3'),
('Spanakopita','2'),
('Spanakopita','3'),
('Baklava','4'),
('Omelette',''),
('Omelette','6'),
('Margherita Pizza','3'),
('Chicken Caesar Salad','2'),
('Chicken Caesar Salad','7'),
('Apple Pie','4'),
('Beef Stir-Fry','5'),
('Beef Stir-Fry','3'),
('Chocolate Cake','4'),
('Falafel','5'),
('Falafel','3'),
('Lemon Bars','4'),
('Shrimp Scampi','3'),
('Beef Tacos','5'),
('Beef Tacos','3'),
('Croque Monsieur','7'),
('Chicken Enchiladas','3'),
('Blueberry Muffins','5'),
('Blueberry Muffins','6'),
('Pad See Ew','5'),
('Pad See Ew','3'),
('Shepherds Pie','3'),
('Tuna Salad Sandwich','7'),
('Tuna Salad Sandwich','5'),
('Miso Soup','3'),
('Miso Soup','2'),
('Key Lime Pie','4'),
('Chicken Tikka Masala','3'),
('Beef Bourguignon','3'),
('Cheese Soufflé','3'),
('Scones','6'),
('Scones','5'),
('Caprese Salad','7'),
('Caprese Salad','2'),
('Beef Bulgogi','3'),
('Chicken Noodle Soup','7'),
('Chicken Noodle Soup','2'),
('Chocolate Truffles','4'),
('Huevos Rancheros','1'),
('Huevos Rancheros','6'),
('Ratatouille','2'),
('Ratatouille','3'),
('Falafel Wrap','5'),
('Falafel Wrap','3'),
('Lemon Chicken Piccata','3'),
('Vegetable Stir-Fry','3'),
('Vegetable Stir-Fry','5'),
('Chicken Alfredo','3'),
('Croissant Bread Pudding','4'),
('Spaghetti Carbonara','3'),
('Chicken Shawarma','3'),
('Chicken Shawarma','5'),
('Red Velvet Cake','4'),
('Margherita Flatbread','3'),
('Gyro Wrap','3'),
('Gyro Wrap','5'),
('Pesto Pasta','3'),
('Chicken Caesar Wrap','7'),
('Chicken Caesar Wrap','5'),
('Mushroom Risotto','3'),
('Avocado Toast','6'),
('Avocado Toast','5'),
('Chicken Quesadilla','3'),
('Chicken Quesadilla','5'),
('French Onion Soup','3'),
('French Onion Soup','2'),
('Lemon Ricotta Pancakes','6'),
('Empanadas','2'),
('Empanadas','5'),
('Lemon Ricotta Pancakes','1'),
('Asado','3'),
('Brigadeiro','4'),
('Feijoada','3'),
('Fritule','4'),
('Pašticada','3'),
('Nasi Goreng','3'),
('Nasi Goreng','5'),
('Sate Ayam','3'),
('Sate Ayam','5'),
('Babi Guling','3'),
('Babi Guling','7'),
('Ameijoas à Bulhão Pato','3'),
('Pão de Ló','1'),
('Pão de Ló','4'),
('Queijadas de Sintra','1'),
('Queijadas de Sintra','4'),
('Churros','4'),
('Paella','3');

INSERT INTO recipe_tip VALUES
('Fluffy Pancakes','14'),
('Fluffy Pancakes','34'),
('Spinach and Feta Quiche','2'),
('Spinach and Feta Quiche','7'),
('Spinach and Feta Quiche','35'),
('Beef Wellington','3'),
('Beef Wellington','14'),
('Beef Wellington','5'),
('Chocolate Chip Cookies','2'),
('Chocolate Chip Cookies','15'),
('Chocolate Chip Cookies','14'),
('Chicken Pad Thai','4'),
('Chicken Pad Thai','15'),
('Chicken Pad Thai','36'),
('Croissant','5'),
('Croissant','16'),
('Croissant','37'),
('Tiramisu','6'),
('Tiramisu','17'),
('Tiramisu','38'),
('Sushi Rolls','7'),
('Sushi Rolls','4'),
('Sushi Rolls','37'),
('Spanakopita','8'),
('Spanakopita','2'),
('Spanakopita','35'),
('Baklava','3'),
('Baklava','7'),
('Baklava','20'),
('Omelette','3'),
('Omelette','15'),
('Omelette','37'),
('Margherita Pizza','7'),
('Margherita Pizza','20'),
('Margherita Pizza','40'),
('Chicken Caesar Salad','7'),
('Chicken Caesar Salad','15'),
('Chicken Caesar Salad','41'),
('Apple Pie','15'),
('Apple Pie','35'),
('Beef Stir-Fry','7'),
('Beef Stir-Fry','15'),
('Beef Stir-Fry','43'),
('Chocolate Cake','7'),
('Chocolate Cake','19'),
('Chocolate Cake','44'),
('Falafel','10'),
('Falafel','20'),
('Falafel','45'),
('Lemon Bars','11'),
('Lemon Bars','21'),
('Lemon Bars','46'),
('Shrimp Scampi','7'),
('Shrimp Scampi','4'),
('Shrimp Scampi','47'),
('Beef Tacos','7'),
('Beef Tacos','22'),
('Beef Tacos','15'),
('Croque Monsieur','7'),
('Croque Monsieur','1'),
('Croque Monsieur','49'),
('Chicken Enchiladas','4'),
('Chicken Enchiladas','23'),
('Chicken Enchiladas','50'),
('Blueberry Muffins','7'),
('Blueberry Muffins','24'),
('Blueberry Muffins','19'),
('Pad See Ew','7'),
('Pad See Ew','15'),
('Shepherds Pie','7'),
('Shepherds Pie','15'),
('Shepherds Pie','35'),
('Tuna Salad Sandwich','7'),
('Tuna Salad Sandwich','15'),
('Tuna Salad Sandwich','53'),
('Miso Soup','7'),
('Miso Soup','15'),
('Miso Soup','54'),
('Key Lime Pie','12'),
('Key Lime Pie','15'),
('Key Lime Pie','35'),
('Chicken Tikka Masala','7'),
('Chicken Tikka Masala','15'),
('Chicken Tikka Masala','56'),
('Beef Bourguignon','7'),
('Beef Bourguignon','1'),
('Beef Bourguignon','17'),
('Cheese Soufflé','7'),
('Cheese Soufflé','1'),
('Cheese Soufflé','57'),
('Scones','7'),
('Scones','1'),
('Scones','58'),
('Caprese Salad','7'),
('Caprese Salad','15'),
('Caprese Salad','59'),
('Beef Bulgogi','7'),
('Beef Bulgogi','15'),
('Beef Bulgogi','60'),
('Chicken Noodle Soup','7'),
('Chicken Noodle Soup','15'),
('Chicken Noodle Soup','35'),
('Chocolate Truffles','7'),
('Chocolate Truffles','27'),
('Chocolate Truffles','61'),
('Huevos Rancheros','7'),
('Huevos Rancheros','15'),
('Huevos Rancheros','62'),
('Ratatouille','7'),
('Ratatouille','1'),
('Ratatouille','63'),
('Falafel Wrap','10'),
('Falafel Wrap','1'),
('Falafel Wrap','64'),
('Lemon Chicken Piccata','7'),
('Lemon Chicken Piccata','15'),
('Lemon Chicken Piccata','66'),
('Vegetable Stir-Fry','7'),
('Vegetable Stir-Fry','15'),
('Vegetable Stir-Fry','67'),
('Chicken Alfredo','7'),
('Chicken Alfredo','15'),
('Chicken Alfredo','68'),
('Croissant Bread Pudding','2'),
('Croissant Bread Pudding','30'),
('Croissant Bread Pudding','1'),
('Spaghetti Carbonara','7'),
('Spaghetti Carbonara','15'),
('Spaghetti Carbonara','69'),
('Chicken Shawarma','7'),
('Chicken Shawarma','15'),
('Chicken Shawarma','70'),
('Red Velvet Cake','7'),
('Red Velvet Cake','1'),
('Red Velvet Cake','71'),
('Margherita Flatbread','7'),
('Margherita Flatbread','18'),
('Margherita Flatbread','40'),
('Gyro Wrap','7'),
('Gyro Wrap','15'),
('Gyro Wrap','64'),
('Pesto Pasta','7'),
('Pesto Pasta','15'),
('Pesto Pasta','72'),
('Chicken Caesar Wrap','7'),
('Chicken Caesar Wrap','15'),
('Chicken Caesar Wrap','41'),
('Mushroom Risotto','7'),
('Mushroom Risotto','1'),
('Mushroom Risotto','69'),
('Avocado Toast','7'),
('Avocado Toast','15'),
('Avocado Toast','73'),
('Chicken Quesadilla','7'),
('Chicken Quesadilla','15'),
('Chicken Quesadilla','74'),
('French Onion Soup','7'),
('French Onion Soup','1'),
('French Onion Soup','75'),
('Lemon Ricotta Pancakes','13'),
('Lemon Ricotta Pancakes','33'),
('Lemon Ricotta Pancakes','76'),
('Empanadas','11'),
('Empanadas','6'),
('Asado','60'),
('Asado','57'),
('Brigadeiro','17'),
('Brigadeiro','14'),
('Feijoada','17'),
('Feijoada','51'),
('Fritule','20'),
('Fritule','54'),
('Pašticada','25'),
('Pašticada','53'),
('Nasi Goreng','15'),
('Nasi Goreng','67'),
('Sate Ayam','65'),
('Sate Ayam','61'),
('Babi Guling','52'),
('Babi Guling','39'),
('Ameijoas à Bulhão Pato','47'),
('Ameijoas à Bulhão Pato','48'),
('Pão de Ló','13'),
('Pão de Ló','14'),
('Queijadas de Sintra','42'),
('Queijadas de Sintra','41'),
('Churros','20'),
('Churros','22'),
('Paella','18'),
('Paella','51');